version: '3'

services:
  app:
    depends_on:
      - postgres
    container_name: stonesign-corelab
    #image: stonesign:latest
    restart: unless-stopped
    build:
      context: .
    expose:
      - "80"
#    ports:
#      - 3000:3000
    networks:
      - stone_network
    volumes:
      - .:/data
    environment:
      - HOST=stonesign.corelab.com.br
      - DATABASE_URL=postgresql://postgres:postgres@postgres_stonesign-corelab:5432/stonesign-corelab
#      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/stonesign-corelab
    links:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres_stonesign-corelab
    restart: unless-stopped
    volumes:
      - stone_pg_data:/var/lib/postgresql/data
    networks:
      - stone_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stonesign-corelab

networks:
  stone_network:
    driver: "bridge"

volumes:
  stone_pg_data:
    driver: "local"
