version: '3'

services:
  app:
    container_name: stonesign-corelab
    image: registry.corelab.com.br:5000/stonesign-corelab:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - stonesign-corelab-network
    volumes:
      - .:/data
    env_file:
      - .env   # pega as variáveis na pasta do projeto no servidor

networks:
  stonesign-corelab-network:
    driver: "bridge"
