name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Login no registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push StoneSign
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_REGISTRY }}/stonesign-corelab:latest
          cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/stonesign-corelab:buildcache
          cache-to: type=registry,ref=${{ vars.DOCKER_REGISTRY }}/stonesign-corelab:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Atualizar Imagem e Executar
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker login ${{ vars.DOCKER_REGISTRY }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
            cd ~/stonesign-corelab
            docker-compose down
            docker-compose pull
            docker-compose up -d
